# Generated by Django 6.0.6 on 2026-07-07 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de descuento (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
